### PR TITLE
Dfl Win64 support

### PR DESCRIPTION
**Pull request by qchikara**
# This will be closed -- superceded by #49 and #50

## Goal
1. Minimal patches.
2. No breaking change to win32 programs.

## Fix compile error
Fix Dozens of size_t conversion error.

Add toI32 helper function instead of type cast.

Especially, collection helpers are rather complicated.

### Update WIn32 APIs
1. SetWindowLong family.
SetWindowLong -> SetWindowLongPtr, and so on.
2. Common dialogs: structures and callbacks.
UINT -> UINT_PTR, and so on.
3. Windows timer functions: callbacks.

### Fix application manifest
embedded in dfl/application.d.

### Add makewin64.bat
It requires fix by each user -- MSVC paths.

It is not called by go.bat. (But maybe it should be...)
### Fix dfl.exe
Switch linker flags when -m64 specified.

### CODE REVIEW

**Comment by Rayerd** [comment]
Need to compile MSVC?

**Comment by qchikara** [comment]
Yes. Win64-support by DMD requires the _linker_ in MSVC (and the import libraries included, too).

If you are going to install it newly, you had better run the dmd installer after MSVC.
It will configure the tools paths.
Moreover, please fix the makewin64.bat in DFL, as I wrote above.

Thanks.

**Comment by Rayerd** [comment]
Because I cannot compile it well, I have not been able to yet inspect your pull request.

**Comment by qchikara** [comment]
Sorry for late reply.

Added a commit.
Now, makewin64 is modified for MSVC2013 Community Edition.

HOWEVER, you might NEED to modify it. Then, please see the description in it.

**Comment by qchikara** [comment]
I'll close this and split into 2 PRs, so we will support the 32-bit COFF format.

**Comment by qchikara** [comment]
closed

**Comment by Rayerd** [comment]
I'm glad about your activity.
But I'm busy, and can't develop DFL.
I'm sorry.

**Pull request closed without merging**
