### PR TITLE
Modify the base.d for D2.065,and add the win64 folder for test

### PR DESCRIPTION
**Pull request by FrankLIKE**
Modify the win32/base.d for D2.065
Add the new folder win64 for test,it come from win32,and modify :set int =cast(int)size_t.

### CODE REVIEW

**Comment by Rayerd** [comment]
Is this PR valid?

**Comment by FrankLIKE** [comment]
Thank you start work again,I thought you were giving up on DFL, so start dfl2:
https://github.com/FrankLIKE/dfl2,if DFL is ok,I will stop it.
But 'https://github.com/FrankLIKE/dco' is good,for building dfl exe.

**Comment by Rayerd** [comment]
Thank you.
I like DFL, but I am so busy now.

I think that dfl.exe don't need already.
What do you think?

**Comment by Rayerd** [comment]
Do we need different source code for win64 than win32?

**Pull request closed without merging**
